theme: jekyll-theme-giellalt
title: Dictionary for Plains Cree ⇒ English
description: An electronic dictionary from Plains Cree to English

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
